local broadcast = require "ludobits.m.broadcast"
local camera = require("orthographic.camera")
local messages = require "cfg.messages"

function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	local xy = camera.screen_to_world(nil, vmath.vector3(action.screen_x, action.screen_y, 0))

	local isPressed = action_id == hash("touch") and action.pressed
	broadcast.send(messages.GAME_INPUT, {
		xy = xy,
		pressed = isPressed,
		released = action.released
	})
end
