local evolved = require "lib.evolved"
local gcmp = require("ecs.features.gameobject_feature.components")
local icmp = require("ecs.features.input_feature.components")
local gpcmp=  require("ecs.features.gameplay_feature.components")
local dcmp = require("ecs.features.drag_feature.components")

local cfg = require("cfg.cfg")

local function use_feature(self, feature)
	for _, system in ipairs(feature) do
		self.systems[#self.systems + 1] = system
	end
end

local function create(path)
	local id = go.get_id(path)

	local ety = evolved.id()
	evolved.set(ety, gcmp.GameobjectId, id)
	evolved.set(ety, gpcmp.Source, msg.url("/root#figure_factory"))
	evolved.set(ety, gpcmp.RollFigure, true)
	--evolved.set(ety, dcmp.Draggable, true)
	go.set(msg.url(nil, id, "input"), "entity", ety)
end

function init(self)
	msg.post(".", "acquire_input_focus")

	self.systems = {}
	
	use_feature(self, require("ecs.features.gameobject_feature.feature").process)
	use_feature(self, require("ecs.features.drag_feature.feature").process)
	use_feature(self, require("ecs.features.gameplay_feature.feature").process)
	use_feature(self, require("ecs.features.gameobject_feature.feature").postprocess)
	use_feature(self, require("ecs.features.core_feature.feature").postprocess)

	create("/logo_spawner")
	create("/logo_spawner1")

	self.global_input = icmp.InputAction
	evolved.set(self.global_input, icmp.InputAction, true)
end

function update(self, dt)
	for i = 1, #self.systems do
		evolved.process_with(self.systems[i], dt)
	end
end

function on_input(self, action_id, action)
end